# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.mcodeomop
canonical: http://mcodeomop.example.org
title: "mCODE to OMOP Oncology CDM Analysis"
name: mcodeomop
status: draft
description: "This FHIR implementation guide (IG) is a FHIR analysis to compare mCODE elements with OMOP CDM Oncology. This serves more as a document with computable FHIR examples. Profiles and value sets may be generated but it is secondary and created in support of further analyses. The output of this artifact may be merged into mCODE and supplementary content if relevant and appropriate."
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
pages:
  index.md:
    title: Home

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
